# Generated by Django 3.1.7 on 2021-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('breakfast', 'завтрак'), ('first meal', 'первые блюда'), ('second courses', 'вторые блюда'), ('the drinks', 'напитки '), ('other', 'разное')], default='other', max_length=32)),
                ('remainder', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
            },
        ),
    ]
